import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { DBUserProvider } from '@/context/DBUserContext';
import Providers from "@/components/Providers";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      {/* <DBUserProvider> */}
      <Providers>
      <body 
      style={{
        backgroundImage: 'linear-gradient(120deg, #fdfbfb 0%, #ebedee 100%)',
      }}
      className={inter.className}>
        <Toaster position="bottom-center" />
        {children}
      </body>
      </Providers>
      {/* </DBUserProvider> */}
    </html>
  );
}
